package db;
// Generated Feb 10, 2017 9:46:45 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Festival generated by hbm2java
 */
public class Festival  implements java.io.Serializable {


     private Long idFes;
     private String naziv;
     private Date datumOd;
     private Date datumDo;
     private String mesto;
     private String detalji;
     private int kapacitetPoDanu;
     private int maxKarataPoKorisniku;
     private int cenaPaket;
     private int cenaDan;
     private long pregledi;
     private String facebook;
     private String twitter;
     private String instagram;
     private String youtube;
     private boolean otkazano;
     private int brojKupljenih;
     private Set<Galerija> galerijas = new HashSet<Galerija>(0);
     private Set<Ocena> ocenas = new HashSet<Ocena>(0);
     private Set<Ulaznica> ulaznicas = new HashSet<Ulaznica>(0);
     private Set<Nastup> nastups = new HashSet<Nastup>(0);

    public Festival() {
    }

	
    public Festival(String naziv, Date datumOd, Date datumDo, String mesto, String detalji, int kapacitetPoDanu, int maxKarataPoKorisniku, int cenaPaket, int cenaDan, long pregledi, boolean otkazano, int brojKupljenih) {
        this.naziv = naziv;
        this.datumOd = datumOd;
        this.datumDo = datumDo;
        this.mesto = mesto;
        this.detalji = detalji;
        this.kapacitetPoDanu = kapacitetPoDanu;
        this.maxKarataPoKorisniku = maxKarataPoKorisniku;
        this.cenaPaket = cenaPaket;
        this.cenaDan = cenaDan;
        this.pregledi = pregledi;
        this.otkazano = otkazano;
        this.brojKupljenih = brojKupljenih;
    }
    public Festival(String naziv, Date datumOd, Date datumDo, String mesto, String detalji, int kapacitetPoDanu, int maxKarataPoKorisniku, int cenaPaket, int cenaDan, long pregledi, String facebook, String twitter, String instagram, String youtube, boolean otkazano, int brojKupljenih, Set<Galerija> galerijas, Set<Ocena> ocenas, Set<Ulaznica> ulaznicas, Set<Nastup> nastups) {
       this.naziv = naziv;
       this.datumOd = datumOd;
       this.datumDo = datumDo;
       this.mesto = mesto;
       this.detalji = detalji;
       this.kapacitetPoDanu = kapacitetPoDanu;
       this.maxKarataPoKorisniku = maxKarataPoKorisniku;
       this.cenaPaket = cenaPaket;
       this.cenaDan = cenaDan;
       this.pregledi = pregledi;
       this.facebook = facebook;
       this.twitter = twitter;
       this.instagram = instagram;
       this.youtube = youtube;
       this.otkazano = otkazano;
       this.brojKupljenih = brojKupljenih;
       this.galerijas = galerijas;
       this.ocenas = ocenas;
       this.ulaznicas = ulaznicas;
       this.nastups = nastups;
    }
   
    public Long getIdFes() {
        return this.idFes;
    }
    
    public void setIdFes(Long idFes) {
        this.idFes = idFes;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public Date getDatumOd() {
        return this.datumOd;
    }
    
    public void setDatumOd(Date datumOd) {
        this.datumOd = datumOd;
    }
    public Date getDatumDo() {
        return this.datumDo;
    }
    
    public void setDatumDo(Date datumDo) {
        this.datumDo = datumDo;
    }
    public String getMesto() {
        return this.mesto;
    }
    
    public void setMesto(String mesto) {
        this.mesto = mesto;
    }
    public String getDetalji() {
        return this.detalji;
    }
    
    public void setDetalji(String detalji) {
        this.detalji = detalji;
    }
    public int getKapacitetPoDanu() {
        return this.kapacitetPoDanu;
    }
    
    public void setKapacitetPoDanu(int kapacitetPoDanu) {
        this.kapacitetPoDanu = kapacitetPoDanu;
    }
    public int getMaxKarataPoKorisniku() {
        return this.maxKarataPoKorisniku;
    }
    
    public void setMaxKarataPoKorisniku(int maxKarataPoKorisniku) {
        this.maxKarataPoKorisniku = maxKarataPoKorisniku;
    }
    public int getCenaPaket() {
        return this.cenaPaket;
    }
    
    public void setCenaPaket(int cenaPaket) {
        this.cenaPaket = cenaPaket;
    }
    public int getCenaDan() {
        return this.cenaDan;
    }
    
    public void setCenaDan(int cenaDan) {
        this.cenaDan = cenaDan;
    }
    public long getPregledi() {
        return this.pregledi;
    }
    
    public void setPregledi(long pregledi) {
        this.pregledi = pregledi;
    }
    public String getFacebook() {
        return this.facebook;
    }
    
    public void setFacebook(String facebook) {
        this.facebook = facebook;
    }
    public String getTwitter() {
        return this.twitter;
    }
    
    public void setTwitter(String twitter) {
        this.twitter = twitter;
    }
    public String getInstagram() {
        return this.instagram;
    }
    
    public void setInstagram(String instagram) {
        this.instagram = instagram;
    }
    public String getYoutube() {
        return this.youtube;
    }
    
    public void setYoutube(String youtube) {
        this.youtube = youtube;
    }
    public boolean isOtkazano() {
        return this.otkazano;
    }
    
    public void setOtkazano(boolean otkazano) {
        this.otkazano = otkazano;
    }
    public int getBrojKupljenih() {
        return this.brojKupljenih;
    }
    
    public void setBrojKupljenih(int brojKupljenih) {
        this.brojKupljenih = brojKupljenih;
    }
    public Set<Galerija> getGalerijas() {
        return this.galerijas;
    }
    
    public void setGalerijas(Set<Galerija> galerijas) {
        this.galerijas = galerijas;
    }
    public Set<Ocena> getOcenas() {
        return this.ocenas;
    }
    
    public void setOcenas(Set<Ocena> ocenas) {
        this.ocenas = ocenas;
    }
    public Set<Ulaznica> getUlaznicas() {
        return this.ulaznicas;
    }
    
    public void setUlaznicas(Set<Ulaznica> ulaznicas) {
        this.ulaznicas = ulaznicas;
    }
    public Set<Nastup> getNastups() {
        return this.nastups;
    }
    
    public void setNastups(Set<Nastup> nastups) {
        this.nastups = nastups;
    }
}


