package db;
// Generated Feb 10, 2017 9:46:45 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Korisnik generated by hbm2java
 */
public class Korisnik  implements java.io.Serializable {


     private Long idKor;
     private String ime;
     private String prezime;
     private String username;
     private String password;
     private String telefon;
     private String email;
     private boolean admin;
     private boolean odobren;
     private Date poslednjaPrijava;
     private int brojUpozorenja;
     private Set<Ulaznica> ulaznicas = new HashSet<Ulaznica>(0);
     private Set<Notifikacija> notifikacijas = new HashSet<Notifikacija>(0);
     private Set<Ocena> ocenas = new HashSet<Ocena>(0);

    public Korisnik() {
    }

	
    public Korisnik(String ime, String prezime, String username, String password, String telefon, String email, boolean admin, boolean odobren, Date poslednjaPrijava, int brojUpozorenja) {
        this.ime = ime;
        this.prezime = prezime;
        this.username = username;
        this.password = password;
        this.telefon = telefon;
        this.email = email;
        this.admin = admin;
        this.odobren = odobren;
        this.poslednjaPrijava = poslednjaPrijava;
        this.brojUpozorenja = brojUpozorenja;
    }
    public Korisnik(String ime, String prezime, String username, String password, String telefon, String email, boolean admin, boolean odobren, Date poslednjaPrijava, int brojUpozorenja, Set<Ulaznica> ulaznicas, Set<Notifikacija> notifikacijas, Set<Ocena> ocenas) {
       this.ime = ime;
       this.prezime = prezime;
       this.username = username;
       this.password = password;
       this.telefon = telefon;
       this.email = email;
       this.admin = admin;
       this.odobren = odobren;
       this.poslednjaPrijava = poslednjaPrijava;
       this.brojUpozorenja = brojUpozorenja;
       this.ulaznicas = ulaznicas;
       this.notifikacijas = notifikacijas;
       this.ocenas = ocenas;
    }
   
    public Long getIdKor() {
        return this.idKor;
    }
    
    public void setIdKor(Long idKor) {
        this.idKor = idKor;
    }
    public String getIme() {
        return this.ime;
    }
    
    public void setIme(String ime) {
        this.ime = ime;
    }
    public String getPrezime() {
        return this.prezime;
    }
    
    public void setPrezime(String prezime) {
        this.prezime = prezime;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getTelefon() {
        return this.telefon;
    }
    
    public void setTelefon(String telefon) {
        this.telefon = telefon;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public boolean isAdmin() {
        return this.admin;
    }
    
    public void setAdmin(boolean admin) {
        this.admin = admin;
    }
    public boolean isOdobren() {
        return this.odobren;
    }
    
    public void setOdobren(boolean odobren) {
        this.odobren = odobren;
    }
    public Date getPoslednjaPrijava() {
        return this.poslednjaPrijava;
    }
    
    public void setPoslednjaPrijava(Date poslednjaPrijava) {
        this.poslednjaPrijava = poslednjaPrijava;
    }
    public int getBrojUpozorenja() {
        return this.brojUpozorenja;
    }
    
    public void setBrojUpozorenja(int brojUpozorenja) {
        this.brojUpozorenja = brojUpozorenja;
    }
    public Set<Ulaznica> getUlaznicas() {
        return this.ulaznicas;
    }
    
    public void setUlaznicas(Set<Ulaznica> ulaznicas) {
        this.ulaznicas = ulaznicas;
    }
    public Set<Notifikacija> getNotifikacijas() {
        return this.notifikacijas;
    }
    
    public void setNotifikacijas(Set<Notifikacija> notifikacijas) {
        this.notifikacijas = notifikacijas;
    }
    public Set<Ocena> getOcenas() {
        return this.ocenas;
    }
    
    public void setOcenas(Set<Ocena> ocenas) {
        this.ocenas = ocenas;
    }




}


