package db;
// Generated Feb 10, 2017 9:46:45 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Nastup generated by hbm2java
 */
public class Nastup  implements java.io.Serializable {


     private Long idNas;
     private Festival festival;
     private String izvodjac;
     private Date datumOd;
     private Date datumDo;
     private Date vremeOd;
     private Date vremeDo;
     private boolean otkazano;

    public Nastup() {
    }

    public Nastup(Festival festival, String izvodjac, Date datumOd, Date datumDo, Date vremeOd, Date vremeDo, boolean otkazano) {
       this.festival = festival;
       this.izvodjac = izvodjac;
       this.datumOd = datumOd;
       this.datumDo = datumDo;
       this.vremeOd = vremeOd;
       this.vremeDo = vremeDo;
       this.otkazano = otkazano;
    }
   
    public Long getIdNas() {
        return this.idNas;
    }
    
    public void setIdNas(Long idNas) {
        this.idNas = idNas;
    }
    public Festival getFestival() {
        return this.festival;
    }
    
    public void setFestival(Festival festival) {
        this.festival = festival;
    }
    public String getIzvodjac() {
        return this.izvodjac;
    }
    
    public void setIzvodjac(String izvodjac) {
        this.izvodjac = izvodjac;
    }
    public Date getDatumOd() {
        return this.datumOd;
    }
    
    public void setDatumOd(Date datumOd) {
        this.datumOd = datumOd;
    }
    public Date getDatumDo() {
        return this.datumDo;
    }
    
    public void setDatumDo(Date datumDo) {
        this.datumDo = datumDo;
    }
    public Date getVremeOd() {
        return this.vremeOd;
    }
    
    public void setVremeOd(Date vremeOd) {
        this.vremeOd = vremeOd;
    }
    public Date getVremeDo() {
        return this.vremeDo;
    }
    
    public void setVremeDo(Date vremeDo) {
        this.vremeDo = vremeDo;
    }
    public boolean isOtkazano() {
        return this.otkazano;
    }
    
    public void setOtkazano(boolean otkazano) {
        this.otkazano = otkazano;
    }




}


