package db;
// Generated Feb 10, 2017 9:46:45 PM by Hibernate Tools 4.3.1



/**
 * Notifikacija generated by hbm2java
 */
public class Notifikacija  implements java.io.Serializable {


     private Long idNot;
     private Korisnik korisnik;
     private String tekst;
     private boolean pregledano;

    public Notifikacija() {
    }

    public Notifikacija(Korisnik korisnik, String tekst, boolean pregledano) {
       this.korisnik = korisnik;
       this.tekst = tekst;
       this.pregledano = pregledano;
    }
   
    public Long getIdNot() {
        return this.idNot;
    }
    
    public void setIdNot(Long idNot) {
        this.idNot = idNot;
    }
    public Korisnik getKorisnik() {
        return this.korisnik;
    }
    
    public void setKorisnik(Korisnik korisnik) {
        this.korisnik = korisnik;
    }
    public String getTekst() {
        return this.tekst;
    }
    
    public void setTekst(String tekst) {
        this.tekst = tekst;
    }
    public boolean isPregledano() {
        return this.pregledano;
    }
    
    public void setPregledano(boolean pregledano) {
        this.pregledano = pregledano;
    }




}


