package db;
// Generated Feb 10, 2017 9:46:45 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Ulaznica generated by hbm2java
 */
public class Ulaznica  implements java.io.Serializable {


     private Long idUla;
     private Festival festival;
     private Korisnik korisnik;
     private Date datumNastupa;
     private int kolicina;
     private Date vremeKreiranja;
     private boolean prodato;
     private boolean isteklo;

    public Ulaznica() {
    }

	
    public Ulaznica(Festival festival, Korisnik korisnik, int kolicina, Date vremeKreiranja, boolean prodato, boolean isteklo) {
        this.festival = festival;
        this.korisnik = korisnik;
        this.kolicina = kolicina;
        this.vremeKreiranja = vremeKreiranja;
        this.prodato = prodato;
        this.isteklo = isteklo;
    }
    public Ulaznica(Festival festival, Korisnik korisnik, Date datumNastupa, int kolicina, Date vremeKreiranja, boolean prodato, boolean isteklo) {
       this.festival = festival;
       this.korisnik = korisnik;
       this.datumNastupa = datumNastupa;
       this.kolicina = kolicina;
       this.vremeKreiranja = vremeKreiranja;
       this.prodato = prodato;
       this.isteklo = isteklo;
    }
   
    public Long getIdUla() {
        return this.idUla;
    }
    
    public void setIdUla(Long idUla) {
        this.idUla = idUla;
    }
    public Festival getFestival() {
        return this.festival;
    }
    
    public void setFestival(Festival festival) {
        this.festival = festival;
    }
    public Korisnik getKorisnik() {
        return this.korisnik;
    }
    
    public void setKorisnik(Korisnik korisnik) {
        this.korisnik = korisnik;
    }
    public Date getDatumNastupa() {
        return this.datumNastupa;
    }
    
    public void setDatumNastupa(Date datumNastupa) {
        this.datumNastupa = datumNastupa;
    }
    public int getKolicina() {
        return this.kolicina;
    }
    
    public void setKolicina(int kolicina) {
        this.kolicina = kolicina;
    }
    public Date getVremeKreiranja() {
        return this.vremeKreiranja;
    }
    
    public void setVremeKreiranja(Date vremeKreiranja) {
        this.vremeKreiranja = vremeKreiranja;
    }
    public boolean isProdato() {
        return this.prodato;
    }
    
    public void setProdato(boolean prodato) {
        this.prodato = prodato;
    }
    public boolean isIsteklo() {
        return this.isteklo;
    }
    
    public void setIsteklo(boolean isteklo) {
        this.isteklo = isteklo;
    }




}


